final quotes = [
  '„Nie uczysz się dla szkoły, lecz dla siebie.” - Seneka',
  '„Nauka to potęgi klucz.” - Ignacy Krasicki',
  '„Człowiek uczy się przez całe życie.”',
  '„Wiedza to potęga.”',
  '„Im więcej wiem, tym więcej wiem, że nic nie wiem.” - Sokrates',
  '„Uczyć się to odkrywać to, co już wiesz. Działać to pokazywać, że to wiesz.” - Richard Bach',
  '„Uczenie się jest jak wiosłowanie pod prąd - gdy przestajesz, cofasz się.” - Edward Benjamin Britten',
  '„Kiedy uczymy innych, uczymy się podwójnie.” - Joseph Joubert',
  '„Inwestycja w wiedzę zawsze przynosi największe zyski.” - Benjamin Franklin',
  '„Nie ma większej siły niż wiedza i nie ma większej wolności niż edukacja.” - Malcolm X',
  '„Edukacja jest najpotężniejszą bronią, której możesz użyć, aby zmienić świat.” - Nelson Mandela',
  '„Nauka bez myślenia jest bezużyteczna. Myślenie bez nauki - niebezpieczne.” - Konfucjusz',
  '„Błąd jest dowodem na to, że próbujesz.” - Jennifer Lim',
  '„Ciekawość jest początkiem mądrości.” - Sokrates',
  '„Uczymy się nie dla szkoły, lecz dla życia.” - Seneka Młodszy',
  '„Sukces to suma niewielkiego wysiłku powtarzanego dzień po dniu.” - Robert Collier',
  '„Edukacja to nie wypełnianie wiadra, lecz rozpalanie ognia.” - William Butler Yeats',
  '„Nie musisz być wielki, by zacząć, ale musisz zacząć, by być wielki.” - Zig Ziglar',
  '„Każdy mistrz kiedyś był początkującym.” - Robin Sharma',
  '„Ucz się tak, jakbyś miał żyć wiecznie.” - Gandhi',
  '„Ucz się, ucz, bo nauka to potęgi klucz, a kto ma dużo kluczy... zostaje woźnym.” - Ludowa mądrość z przestrogą',
];
